### ISSUE TITLE
[BUG] Maximum call stack size exceeded

### ISSUE THREAD

**Issue by fluxxdog** [Larkinabout/fvtt-custom-dnd5e#12]
**Describe the bug**
Logger.debug() causes call stack errors. It calls getSetting() which calls Logger.debug() which calls... until the call stack throws an error.

**Versions:**
- Module: fvtt-custom-dnd5e 0.5.0
- System: dnd5e 3.0.2
- Foundry VTT: 11.315 (Stable)
- Browser: built-in

**Additional context**
```
utils.js:18 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at Logger.debug (utils.js:18:9)
    at getSetting (utils.js:111:16)
    at Logger.debug (utils.js:18:30)
    at getSetting (utils.js:111:16)
    at Logger.debug (utils.js:18:30)
    at getSetting (utils.js:111:16)
    at Logger.debug (utils.js:18:30)
    at getSetting (utils.js:111:16)
    at Logger.debug (utils.js:18:30)
    at getSetting (utils.js:111:16)
```

**Comment by Larkinabout** [comment]
Fixed in 0.5.1.
