### ISSUE TITLE
[BUG] Cannot open character sheet

### ISSUE THREAD

**Issue by fluxxdog** [Larkinabout/fvtt-custom-dnd5e#13]
**Describe the bug**
Cannot open character sheets with fvtt-custom-dnd5e active. All settings are default.

**Versions:**
- Module: fvtt-custom-dnd5e 0.5.0
- System: dnd5e 3.0.2
- Foundry VTT: 11.315 (Stable)
- Browser: Built-in

**Additional context**
```
TypeError: An error occurred while rendering ActorSheet5eCharacter2 42. Cannot read properties of undefined (reading 'children')
[Detected 3 packages: system:dnd5e, custom-dnd5e, lib-wrapper]
    at searchCategory (trait.mjs:452:16)
    at searchCategory (trait.mjs:453:26)
    at keyLabel (trait.mjs:458:20)
    at character-sheet-2.mjs:434:32
    at Array.map (<anonymous>)
    at ActorSheet5eCharacter2._prepareTraits (character-sheet-2.mjs:433:23)
    at ActorSheet5eCharacter2.getData (base-sheet.mjs:180:27)
    at ActorSheet5eCharacter2.getData (character-sheet.mjs:24:33)
    at ActorSheet5eCharacter2.getData (character-sheet-2.mjs:183:33)
    at ActorSheet5eCharacter2.renderPatch (application-render.js:28:29)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:591:14)
    at 🎁Application.prototype._render#0 (libWrapper-wrapper.js:189:20)
    at ActorSheet5eCharacter2._render (foundry.js:6532:17)
    at ActorSheet5eCharacter2._render (character-sheet-2.mjs:170:17)
    at ActorSheet5eCharacter2.render (foundry.js:5769:10)
    at ActorSheet5eCharacter2.render (foundry.js:7111:18)
    at ActorDirectory._onClickEntryName (foundry.js:70219:20)
    at HTMLOListElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
```

**Comment by Larkinabout** [comment]
Fixed in 0.5.1.
