### ISSUE TITLE
Can't create a new skill [BUG]

### ISSUE THREAD

**Issue by nileuy** [Larkinabout/fvtt-custom-dnd5e#147]
**Description**

Impossible to create a new skill, it is only possible to edit an existing one.

**Debug**
[custom-dnd5e.json](https://github.com/user-attachments/files/18029361/custom-dnd5e.json)

**Console**
foundry.js:8253 Uncaught (in promise) TypeError: undefined. Cannot convert undefined or null to object
[Detected 1 package: custom-dnd5e(1.2.7)]
    at Function.entries (<anonymous>)
    at Object.selectOptions (foundry.js:8253:36)
    at Object.c (handlebars.min.js:27:27865)
    at eval (eval at createFunctionContext (handlebars.min.js:29:10011), <anonymous>:61:159)
    at h (handlebars.min.js:27:25975)
    at c (handlebars.min.js:27:6943)
    at handlebars.min.js:27:7607
    at Object.<anonymous> (handlebars.min.js:27:7619)
    at Object.c (handlebars.min.js:27:27865)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:10011), <anonymous>:10:52)
    at c (handlebars.min.js:27:23534)
    at d (handlebars.min.js:27:23849)
    at e (handlebars.min.js:28:30886)
    at renderTemplate (foundry.js:7902:10)
    at async SkillsForm._getHtml (config-form.js:519:26)
    at async SkillsForm.createItem (config-form.js:109:26)
selectOptions @ foundry.js:8253
c @ handlebars.min.js:27
eval @ VM259070:61
h @ handlebars.min.js:27
c @ handlebars.min.js:27
(anonymous) @ handlebars.min.js:27
(anonymous) @ handlebars.min.js:27
c @ handlebars.min.js:27
eval @ VM259071:10
c @ handlebars.min.js:27
d @ handlebars.min.js:27
e @ handlebars.min.js:28
renderTemplate @ foundry.js:7902
await in renderTemplate (async)
#onClickAction @ foundry-esm.js:45097
#onClick @ foundry-esm.js:45058

**Versions:**
- Module: [1.2.7]
- System: [dnd5e 4.1.2]
- Foundry VTT: [e.g. 12.331]
- Browser: [Local Host]

**Additional context**
There is no other module installed.

**Comment by Larkinabout** [comment]
Fixed in 1.2.8.
